---
name: mt5_env
channels:
  - conda-forge
  - defaults
dependencies:
  - fastparquet
  - ipykernel
  - matplotlib
  - nbformat
  - pandas
  - pip
  - plotly
  - pyarrow
  - python=3.12
  - sqlite=3.50.2
  - ta-lib
  - pip:
      - metatrader5
